server:
  port: 8080
spring:
  # DB config
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false
  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


#로그 설정
logging:
  level:
    com.sprint.ootd5team: debug
    org.springframework.security: TRACE
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: off # @ConditionalOnClass 로그 숨기기
    org.springframework.boot.autoconfigure: warn
    #SQL 로그
    org.hibernate.SQL: debug                 # 실행되는 SQL
    org.hibernate.orm.jdbc.bind: trace       # 바인딩 파라미터 값
    org.hibernate.orm.jdbc.extract: trace    # ResultSet에서 값 읽기

management:
  health:
    redis:
      enabled: false