spring:
  application:
    name: OOTD-5Team
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

#외부 API key 설정
weather:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
  kma: #기상청
    client-id: ${KMA_CLIENT_ID}
    client-secret: ${KMA_CLIENT_SECRET}

# Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method

swagger:
  server-url: http://localhost:${server.port}

ootd:
  storage:
    type: local
    s3:
      access-key: ${AWS_S3_ACCESS_KEY:dummy-access-key}
      secret-key: ${AWS_S3_SECRET_KEY:dummy-secret-key}
      region: ${AWS_S3_REGION:ap-northeast-2}
      bucket: ${AWS_S3_BUCKET:zzootd-s3}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
