server:
  port: 8080

logging:
  level:
    root: info

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 5000ms
      connect-timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
        shutdown-timeout: 100ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${CONFLUENT_KAFKA_API_KEY}"
        password="${CONFLUENT_KAFKA_API_SECRET}";
    # Consumer 설정
    consumer:
      group-id: ootd.notification
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    # Producer 설정
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false

  sql:
    init:
      mode: never
  # Elasticsearch 설정
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://10.0.12.90:9200}
    indices:
      feed: feeds-v1

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  # csrf 설정 비활성화/활성화 on off
  csrf:
    enabled: true
  # 웹 MessageQueue Relay 설정
  messaging:
    relay:
      host: ${RABBITMQ_HOST:10.0.12.123}
      port: ${RABBITMQ_STOMP_PORT:61613}
      login: ${RABBITMQ_STOMP_LOGIN:admin}
      passcode: ${RABBITMQ_STOMP_PASSCODE:password1234}
      system-login: ${RABBITMQ_STOMP_SYSTEM_LOGIN:${RABBITMQ_STOMP_LOGIN:admin}}
      system-passcode: ${RABBITMQ_STOMP_SYSTEM_PASSCODE:${RABBITMQ_STOMP_PASSCODE:password1234}}
      virtual-host: ${RABBITMQ_STOMP_VHOST:/}
      heartbeat-send-interval: ${RABBITMQ_STOMP_HEARTBEAT_SEND:10000}
      heartbeat-receive-interval: ${RABBITMQ_STOMP_HEARTBEAT_RECV:10000}
