spring:
  application:
    name: OOTD-5Team
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

# SecurityConfig 비활성화/활성화 on off
app:
  security:
    enabled: true

#외부 API key 설정
weather:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
  kma: #기상청
    client-id: ${KMA_CLIENT_ID}
    client-secret: ${KMA_CLIENT_SECRET}

# Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method

swagger:
  server-url: http://localhost:${server.port}

# Admin 설정
ootd:
  admin:
    username: ${OOTD_ADMIN_USERNAME}
    password: ${OOTD_ADMIN_PASSWORD}
    email: ${OOTD_ADMIN_EMAIL}
    # 임시 비밀번호 전송하는 이메일 설정
  email:
    sender: ${OOTD_EMAIL_SENDER}

  # Access Token 및 Refresh Token 비밀키, 만료시간 설정
  jwt:
    access-token:
      expiration-ms: 1800000 # 30분
      secret: ${JWT_ACCESS_TOKEN_SECRET}

    refresh-token:
      expiration-ms: 604800000 # 7일
      secret: ${JWT_REFRESH_TOKEN_SECRET}
