INSERT INTO tbl_users (id, created_at, updated_at, name, email, password, role, is_locked, temp_password, temp_password_expired_at)
VALUES
    (gen_random_uuid(), NOW() - INTERVAL '90 days', NOW() - INTERVAL '5 days', '캐터피', 'caterpie0@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '85 days', NOW() - INTERVAL '3 days', '버터플', 'butterfree1@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '80 days', NOW() - INTERVAL '1 day', '꼬부기', 'squirtle2@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '78 days', NOW() - INTERVAL '2 hours', '에브이', 'eevee3@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '75 days', NOW() - INTERVAL '6 hours', '구구', 'pidgey4@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '72 days', NOW() - INTERVAL '12 hours', '피카츄', 'pikachu5@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '70 days', NOW() - INTERVAL '8 hours', '버터플', 'butterfree6@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '68 days', NOW() - INTERVAL '4 days', '꼬부기', 'squirtle7@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '65 days', NOW() - INTERVAL '1 hour', '구구', 'pidgey8@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '63 days', NOW() - INTERVAL '15 minutes', '잠만보', 'snorlax9@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '60 days', NOW() - INTERVAL '30 minutes', '뮤', 'mew10@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '58 days', NOW() - INTERVAL '7 days', '꼬부기', 'squirtle11@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '55 days', NOW() - INTERVAL '45 minutes', '뮤', 'mew12@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '53 days', NOW() - INTERVAL '2 hours', '샤미드', 'vaporeon13@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '50 days', NOW() - INTERVAL '3 hours', '피카츄', 'pikachu14@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '48 days', NOW() - INTERVAL '5 hours', '피카츄', 'pikachu15@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '45 days', NOW() - INTERVAL '10 days', '캐터피', 'caterpie16@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '43 days', NOW() - INTERVAL '20 minutes', '꼬부기', 'squirtle17@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '40 days', NOW() - INTERVAL '1 hour 30 minutes', '야도란', 'slowbro18@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '38 days', NOW() - INTERVAL '3 days', '이상해씨', 'bulbasaur19@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '35 days', NOW() - INTERVAL '25 minutes', '구구', 'pidgey20@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '33 days', NOW() - INTERVAL '4 hours', '버터플', 'butterfree21@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '30 days', NOW() - INTERVAL '6 hours', '루기아', 'lugia22@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '28 days', NOW() - INTERVAL '35 minutes', '잠만보', 'snorlax23@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '25 days', NOW() - INTERVAL '2 hours 15 minutes', '라이츄', 'raichu24@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '23 days', NOW() - INTERVAL '8 days', '샤미드', 'vaporeon25@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '20 days', NOW() - INTERVAL '40 minutes', '캐터피', 'caterpie26@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '18 days', NOW() - INTERVAL '50 minutes', '야도란', 'slowbro27@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '15 days', NOW() - INTERVAL '3 hours 20 minutes', '뮤츠', 'mewtwo28@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '13 days', NOW() - INTERVAL '1 hour 45 minutes', '리자몽', 'charizard29@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '10 days', NOW() - INTERVAL '2 days', '루기아', 'lugia30@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '8 days', NOW() - INTERVAL '55 minutes', '샤미드', 'vaporeon31@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '6 days', NOW() - INTERVAL '4 hours 10 minutes', '뮤', 'mew32@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '5 days', NOW() - INTERVAL '10 minutes', '꼬부기', 'squirtle33@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '4 days', NOW() - INTERVAL '5 hours', '마기라스', 'tyranitar34@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '3 days 12 hours', NOW() - INTERVAL '1 day', '부스터', 'flareon35@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '3 days', NOW() - INTERVAL '2 hours 30 minutes', '라이츄', 'raichu36@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 days 18 hours', NOW() - INTERVAL '1 hour 20 minutes', '부스터', 'flareon37@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 days 12 hours', NOW() - INTERVAL '3 hours', '피카츄', 'pikachu38@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 days 6 hours', NOW() - INTERVAL '15 minutes', '부스터', 'flareon39@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 days', NOW() - INTERVAL '45 minutes', '라이츄', 'raichu40@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 day 20 hours', NOW() - INTERVAL '2 hours', '구구', 'pidgey41@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 day 16 hours', NOW() - INTERVAL '4 hours', '부스터', 'flareon42@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 day 12 hours', NOW() - INTERVAL '30 minutes', '부스터', 'flareon43@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 day 8 hours', NOW() - INTERVAL '1 hour', '구구', 'pidgey44@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 day 4 hours', NOW() - INTERVAL '20 minutes', '파이리', 'charmander45@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 hour 15 minutes', '부스터', 'flareon46@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '20 hours', NOW() - INTERVAL '3 hours 45 minutes', '루기아', 'lugia47@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '18 hours', NOW() - INTERVAL '25 minutes', '부스터', 'flareon48@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '16 hours', NOW() - INTERVAL '5 minutes', '마기라스', 'tyranitar49@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '14 hours', NOW() - INTERVAL '2 hours 20 minutes', '뮤츠', 'mewtwo50@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '12 hours', NOW() - INTERVAL '35 minutes', '꼬부기', 'squirtle51@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '10 hours', NOW() - INTERVAL '1 hour 10 minutes', '리자몽', 'charizard52@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '8 hours', NOW() - INTERVAL '40 minutes', '쥬피썬더', 'jolteon53@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '6 hours', NOW() - INTERVAL '50 minutes', '피카츄', 'pikachu54@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '4 hours', NOW() - INTERVAL '1 hour 30 minutes', '에브이', 'eevee55@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '3 hours 30 minutes', NOW() - INTERVAL '15 minutes', '꼬부기', 'squirtle56@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '3 hours', NOW() - INTERVAL '45 minutes', '루기아', 'lugia57@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 hours 45 minutes', NOW() - INTERVAL '25 minutes', '루기아', 'lugia58@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 hours 30 minutes', NOW() - INTERVAL '35 minutes', '이상해씨', 'bulbasaur59@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 hours 15 minutes', NOW() - INTERVAL '55 minutes', '리자몽', 'charizard60@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 hours', NOW() - INTERVAL '10 minutes', '라이츄', 'raichu61@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 hour 45 minutes', NOW() - INTERVAL '20 minutes', '구구', 'pidgey62@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 hour 30 minutes', NOW() - INTERVAL '30 minutes', '루기아', 'lugia63@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 hour 15 minutes', NOW() - INTERVAL '40 minutes', '피카츄', 'pikachu64@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 hour', NOW() - INTERVAL '5 minutes', '부스터', 'flareon65@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '50 minutes', NOW() - INTERVAL '15 minutes', '샤미드', 'vaporeon66@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '45 minutes', NOW() - INTERVAL '25 minutes', '버터플', 'butterfree67@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '40 minutes', NOW() - INTERVAL '35 minutes', '구구', 'pidgey68@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '35 minutes', NOW() - INTERVAL '5 minutes', '뮤', 'mew69@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '10 minutes', '갸라도스', 'gyarados70@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '28 minutes', NOW() - INTERVAL '15 minutes', '샤미드', 'vaporeon71@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '25 minutes', NOW() - INTERVAL '20 minutes', '에브이', 'eevee72@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '23 minutes', NOW() - INTERVAL '3 minutes', '마기라스', 'tyranitar73@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '20 minutes', NOW() - INTERVAL '8 minutes', '샤미드', 'vaporeon74@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '18 minutes', NOW() - INTERVAL '12 minutes', '에브이', 'eevee75@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '15 minutes', NOW() - INTERVAL '5 minutes', '리자몽', 'charizard76@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '13 minutes', NOW() - INTERVAL '8 minutes', '구구', 'pidgey77@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '10 minutes', NOW() - INTERVAL '3 minutes', '꼬부기', 'squirtle78@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '8 minutes', NOW() - INTERVAL '4 minutes', '에브이', 'eevee79@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '7 minutes', NOW() - INTERVAL '2 minutes', '라이츄', 'raichu80@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '6 minutes', NOW() - INTERVAL '4 minutes', '피카츄', 'pikachu81@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '5 minutes', NOW() - INTERVAL '1 minute', '피카츄', 'pikachu82@example.com', 'qwe123', 'ADMIN', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '4 minutes', NOW() - INTERVAL '2 minutes', '꼬부기', 'squirtle83@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '3 minutes 30 seconds', NOW() - INTERVAL '1 minute 30 seconds', '야도란', 'slowbro84@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '3 minutes', NOW() - INTERVAL '1 minute', '갸라도스', 'gyarados85@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 minutes 45 seconds', NOW() - INTERVAL '45 seconds', '갸라도스', 'gyarados86@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 minutes 30 seconds', NOW() - INTERVAL '30 seconds', '잠만보', 'snorlax87@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 minutes 15 seconds', NOW() - INTERVAL '1 minute 15 seconds', '뮤츠', 'mewtwo88@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '2 minutes', NOW() - INTERVAL '1 minute', '마기라스', 'tyranitar89@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 minute 45 seconds', NOW() - INTERVAL '45 seconds', '마기라스', 'tyranitar90@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 minute 30 seconds', NOW() - INTERVAL '30 seconds', '캐터피', 'caterpie91@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 minute 15 seconds', NOW() - INTERVAL '15 seconds', '마기라스', 'tyranitar92@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '1 minute', NOW() - INTERVAL '30 seconds', '야도란', 'slowbro93@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '45 seconds', NOW() - INTERVAL '15 seconds', '이상해씨', 'bulbasaur94@example.com', 'qwe123', 'ADMIN', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '30 seconds', NOW() - INTERVAL '10 seconds', '마기라스', 'tyranitar95@example.com', 'qwe123', 'USER', false, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '25 seconds', NOW() - INTERVAL '5 seconds', '갸라도스', 'gyarados96@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '20 seconds', NOW() - INTERVAL '10 seconds', '뮤', 'mew97@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '15 seconds', NOW() - INTERVAL '5 seconds', '야도란', 'slowbro98@example.com', 'qwe123', 'USER', true, NULL, NULL),
    (gen_random_uuid(), NOW() - INTERVAL '10 seconds', NOW() - INTERVAL '5 seconds', '이상해씨', 'bulbasaur99@example.com', 'qwe123', 'USER', true, NULL, NULL);